### ISSUE TITLE
Installation process it not clear

### ISSUE THREAD

**Issue by ahmlab** [Brainrotlang/brainrot-vscode-extension#1]
I clone the repository but when I try to follow the other steps I just find out by pressing F5 with the project open I only receive this error message:
![image](https://github.com/user-attachments/assets/6dafb602-cac4-4cf0-bed4-08ff49856acf)

How can we complete the installation in order to use Brainrot language? May I request for a installation tutorial guide? I apologize in advance, I'm not very smart but I hope I can try your library.

**Comment by leo-aa88** [comment]
Thanks for pointing this out. I'll update the docs to describe with more detail the process of installation.

**Comment by leo-aa88** [comment]
I've updated the README. Hope it clarifies things now. Let me know if you're still having issues and if not, please close this issue.

**Comment by leo-aa88** [comment]
You can get the latest release from here then load directly into VSCode: https://github.com/araujo88/brainrot-vscode-support/releases/download/v0.0.4/brainrot-0.0.4.vsix

**Comment by AyuBloom** [comment]
> You can get the latest release from here then load directly into VSCode: https://github.com/araujo88/brainrot-vscode-support/releases/download/v0.0.4/brainrot-0.0.4.vsix

I hope you can add this method into the README as well, the two other ones didn't work for me but using the prepackaged .vsix file is much more straightforward.

**Comment by ahmlab** [comment]
First of all thanks for your fast answer and doing the extra work of creating new installing methods, as being said before I'm not very smart and I failed in both methods, please let me share with you my situation with both methods so you can guide, thanks in advance for your help:

Method 1: I reached until step 4 where I found this error
![image](https://github.com/user-attachments/assets/17b6cf99-63a1-4d4b-ac94-9fbff659314b)
The main problem here is that I already have an extension for that

Method 2: I have this error in the terminal with step one when I try to do the packaging

![image](https://github.com/user-attachments/assets/2d0e6655-368a-4180-acfc-f8510303b01e)

I understand that is a little hard to work with newbies like me but I really appreciate your work and really want to try it by myself

**Comment by leo-aa88** [comment]
- Step 1: Download [the latest brainrot vscode extension](https://github.com/araujo88/brainrot-vscode-support/releases/download/v0.0.4/brainrot-0.0.4.vsix)
 - Step 2: Open VSCode
![image](https://github.com/user-attachments/assets/90539f6a-6949-44dc-9d1d-c2afcabd0b88)
 - Step 3: Click on "Extensions"
 ![image](https://github.com/user-attachments/assets/71966ab8-c141-4156-8509-0a32d812380e)
 - Step 4: Click on the tree dots. 
![image](https://github.com/user-attachments/assets/76d5cbca-6994-4ba5-9557-dc9c9906f727)
 - Step 5: Click on "Install from VSIX..." 
![image](https://github.com/user-attachments/assets/23ed7a6c-1ea2-463a-bc5f-1618fbe53782)
 - Locate the .vsix file where you downloaded it and then click on it
 ![image](https://github.com/user-attachments/assets/19e555a1-67f0-4196-97e8-5871087aaa6a)

**Comment by ahmlab** [comment]
Thanks for this explanation for dummies, I can use it now :D
