### ISSUE TITLE
How do I run a .brainrot file?

### ISSUE THREAD

**Issue by ahmlab** [Brainrotlang/brainrot-vscode-extension#5]
How I can run in terminal or even execute a .brainrot file? 

![image](https://github.com/user-attachments/assets/4ff7415e-4a5a-45a6-8516-40a2550ec796)

**Comment by AyuBloom** [comment]
Please refer to the [original repository's README](https://github.com/araujo88/brainrot/blob/main/README.md), but in short, just get its compiler and in your terminal do:
```sh
path/to/brainrot < yourfile.brainrot
```
